### ISSUE TITLE
on/off is not working.

### ISSUE THREAD

**Issue by RoraxHan** [NordicSemiconductor/iOS-nRF-Blinky#3]
I tried android version and that works fine.
but when I try this, I can see this in log.
"LED characteristic is not present, nothing to be done"

**Comment by mostafaberg** [comment]
Has to be a caching issue, iOS caches the GATT table, so sometimes if you have flashed something else previously on a DevKit, the cache will still think it's the same old device.

to fix that , simply put your phone in AirPlane mode for 10 seconds and back again, repeat if you still have the same issue, it will go away after a couple of tries. let me  know if this helps

**Comment by RoraxHan** [comment]
that's not working yet.
I've changed nordicBlinkyServiceUUID and ledCharacteristicUUID.
but I also changed that in android for my device. android version is working.
but iOS version not working.. any suggestion to fix this issue.
my phone is iphone 6s.

**Comment by RoraxHan** [comment]
Oh, sorry! My mistake.
I was going to use only ledCharacteristicUUID.
I set buttonCharacteristicUUID and ledCharacteristicUUID as same.
that's the problem.
```
if aCharacteristic.uuid == BlinkyPeripheral.buttonCharacteristicUUID {
                        print("Discovered Blinky button characteristic")
                        buttonCharacteristic = aCharacteristic
                        enableButtonNotifications(buttonCharacteristic!)
                    } else if aCharacteristic.uuid == BlinkyPeripheral.ledCharacteristicUUID {
                        print("Discovered Blinky LED characteristic")
                        ledCharacteristic = aCharacteristic
                    }
```
in code, if statement  judges buttonCharacteristicUUID first. that was the problem.
Thanks for your support.
