### ISSUE TITLE
LED stuck "Reading..."

### ISSUE THREAD

**Issue by ecarthi** [NordicSemiconductor/iOS-nRF-Blinky#7]
Hi, running this app, the LED here gets stuck "Reading..." and the last output is "Discovered Blinky LED characteristic." Any idea what could cause this?

**Comment by philips77** [comment]
Hi,
Sorry for the long delay. Did you manage to solve the issue? 
Did the issue happen every time or occasionally?
Did you modify the LED Button (blinky) service in Nordic's sample? Which SDK are you using for testing?
